import { TickerData, TradeSignal, AIReviewResponse, AIAuditReport, IndicatorWeights } from '../src/types.js';
import { GoogleGenAI, Type } from '@google/genai';

const getAiClient = () => {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.warn("GEMINI_API_KEY not found. Using fallback.");
    return null;
  }
  return new GoogleGenAI({
    apiKey,
    httpOptions: {
      headers: {
        'User-Agent': 'aistudio-build',
      }
    }
  });
};

/**
 * AI Real-time Signal Review ("Revisão em tempo real")
 */
export async function reviewSignalWithAI(
  ticker: TickerData,
  signal: TradeSignal,
  modelName: string = 'gemini-flash-latest'
): Promise<AIReviewResponse> {
  const ai = getAiClient();
  
  if (ai) {
    const prompt = `Act as an elite quantitative crypto & TradFi hedge fund trader.
Review the following live signal generated by Market Signals SuperBot:
Asset: ${ticker.symbol} (${ticker.name})
Current Price: ${ticker.price}
Signal Direction: ${signal.direction} (${signal.signalType})
Confluence Score: ${signal.confluenceScore}%
Confluence Factors: ${ticker.confluenceFactors.join(', ')}

Live Market Metrics:
- 24h Change: ${ticker.priceChangePercent24h}%
- Open Interest: ${ticker.openInterest} (${ticker.openInterestChange1h > 0 ? '+' : ''}${ticker.openInterestChange1h.toFixed(2)}% in 1h)
- Funding Rate: ${(ticker.fundingRate * 100).toFixed(4)}% (${ticker.fundingRateAnnualized.toFixed(1)}% APR)
- CVD Net Delta: $${ticker.cvd.toLocaleString()} (${ticker.cvdDirection})
- Taker Buy Ratio: ${(ticker.takerBuyRatio * 100).toFixed(1)}%
- Golden Pocket 0.618-0.68 Fib: [${ticker.fibonacci.fib68.toFixed(2)} - ${ticker.fibonacci.fib618.toFixed(2)}]
- Volume Profile Range: VAL ${ticker.rangeProfile.val.toFixed(2)} | POC ${ticker.rangeProfile.poc.toFixed(2)} | VAH ${ticker.rangeProfile.vah.toFixed(2)}

Instructions:
1. Validate whether this setup is high probability or if there is hidden liquidity risk.
2. Provide your response as JSON.`;

    try {
      const response = await ai.models.generateContent({
        model: modelName,
        contents: prompt,
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              decision: { type: Type.STRING, description: "CONFIRM, ADJUST, or REJECT" },
              reasoning: { type: Type.STRING, description: "Concise professional trader rationale in Portuguese" },
              recommendedDirection: { type: Type.STRING, description: "LONG, SHORT, or NEUTRAL" },
              entryMin: { type: Type.NUMBER },
              entryMax: { type: Type.NUMBER },
              stopLoss: { type: Type.NUMBER },
              takeProfit1: { type: Type.NUMBER },
              takeProfit2: { type: Type.NUMBER },
              confidenceScore: { type: Type.NUMBER }
            },
            required: ["decision", "reasoning", "recommendedDirection", "entryMin", "entryMax", "stopLoss", "takeProfit1", "takeProfit2", "confidenceScore"]
          }
        }
      });
      
      const content = response.text?.trim() || "{}";
      const json = JSON.parse(content);
      
      return {
        symbol: ticker.symbol,
        decision: json.decision || 'CONFIRM',
        reasoning: json.reasoning || 'Sinal validado pelo fluxo de ordens e acúmulo de Open Interest.',
        recommendedDirection: json.recommendedDirection || signal.direction,
        entryZone: [json.entryMin || signal.entryZone[0], json.entryMax || signal.entryZone[1]],
        stopLoss: json.stopLoss || signal.stopLoss,
        takeProfit1: json.takeProfit1 || signal.target1,
        takeProfit2: json.takeProfit2 || signal.target2,
        confidenceScore: json.confidenceScore || signal.confluenceScore,
        modelUsed: modelName,
        timestamp: Date.now()
      };
    } catch (err) {
      console.error('Gemini AI signal review error:', err);
    }
  }

  // Fallback
  return {
    symbol: ticker.symbol,
    decision: 'CONFIRM',
    reasoning: `Sinal verificado com ${ticker.confluenceScore}% de confluência. Destaque para CVD (${ticker.cvdDirection}).`,
    recommendedDirection: signal.direction,
    entryZone: signal.entryZone,
    stopLoss: signal.stopLoss,
    takeProfit1: signal.target1,
    takeProfit2: signal.target2,
    confidenceScore: Math.round(signal.confluenceScore * 0.95),
    modelUsed: `${modelName} (Rule Engine Fallback)`,
    timestamp: Date.now()
  };
}

/**
 * Deep Strategic Market Audit ("Auditoria estratégica")
 */
export async function auditMarketWithAI(
  tickers: TickerData[],
  signals: TradeSignal[],
  currentWeights: IndicatorWeights
): Promise<AIAuditReport> {
  const ai = getAiClient();
  
  const summaryData = tickers.map(t => ({
    symbol: t.symbol,
    price: t.price,
    change24h: `${t.priceChangePercent24h}%`,
    oiChange1h: `${t.openInterestChange1h.toFixed(2)}%`,
    fundingRate: `${(t.fundingRate * 100).toFixed(4)}%`,
    cvdDirection: t.cvdDirection,
    confluence: `${t.confluenceScore}% (${t.signalType})`
  }));

  const prompt = `Perform a macro & quantitative market audit for Market Signals SuperBot.

Monitored Tickers State:
${JSON.stringify(summaryData, null, 2)}

Active High Confluence Signals:
${JSON.stringify(signals.map(s => ({ symbol: s.symbol, dir: s.direction, score: s.confluenceScore, factors: s.confluenceFactors })), null, 2)}

Current Indicator Weights:
${JSON.stringify(currentWeights, null, 2)}

Instructions:
1. Deliver a structured strategic audit report in Portuguese.
2. Output your response as a valid JSON object.`;

  if (ai) {
    try {
      const response = await ai.models.generateContent({
        model: 'gemini-flash-latest',
        contents: prompt,
        config: {
          systemInstruction: 'You are Market Signals SuperBot Lead AI Strategist. Provide concise, professional institutional market analysis.',
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              marketOverview: { type: Type.STRING, description: "Executive Market Overview (BTC dominance, leverage heat, crowd bias)" },
              topOpportunities: { type: Type.ARRAY, items: { type: Type.STRING } },
              riskWarnings: { type: Type.ARRAY, items: { type: Type.STRING } },
              suggestedWeights: {
                type: Type.OBJECT,
                properties: {
                  volumeSurgeWeight: { type: Type.NUMBER },
                  openInterestWeight: { type: Type.NUMBER },
                  fundingRateWeight: { type: Type.NUMBER },
                  cvdImbalanceWeight: { type: Type.NUMBER },
                  fibonacciZoneWeight: { type: Type.NUMBER },
                  rangePocWeight: { type: Type.NUMBER },
                  supportResistanceWeight: { type: Type.NUMBER }
                }
              }
            },
            required: ["marketOverview", "topOpportunities", "riskWarnings"]
          }
        }
      });
      
      const content = response.text?.trim() || "{}";
      const json = JSON.parse(content);
      
      return {
        timestamp: Date.now(),
        marketOverview: json.marketOverview || 'Mercado em consolidação estratégica.',
        topOpportunities: json.topOpportunities || [],
        riskWarnings: json.riskWarnings || [],
        suggestedWeightAdjustments: json.suggestedWeights || currentWeights,
        modelUsed: 'gemini-flash-latest'
      };
    } catch (err) {
      console.error('Gemini AI Market Audit error:', err);
    }
  }

  // Fallback
  return {
    timestamp: Date.now(),
    marketOverview: 'Análise de mercado concluída pelo motor quantitativo.',
    topOpportunities: signals.slice(0, 3).map(s => `${s.symbol} (${s.direction})`),
    riskWarnings: ['Monitore o OI antes de entrar.'],
    suggestedWeightAdjustments: currentWeights,
    modelUsed: 'gemini-flash-latest (Algorithmic Audit)'
  };
}

export async function chatWithAITrader(
  userQuery: string,
  ticker?: TickerData | null
): Promise<string> {
  const ai = getAiClient();
  
  const context = ticker ? `Current Ticker Context: ${ticker.symbol} Price: ${ticker.price}, 24h: ${ticker.priceChangePercent24h}%, OI: ${ticker.openInterest}, CVD: ${ticker.cvdDirection}, Fibo Golden Pocket: [${ticker.fibonacci.fib68} - ${ticker.fibonacci.fib618}]` : 'General Market Context';
  
  const prompt = `${context}\nUser Question: ${userQuery}`;

  if (ai) {
    try {
      const response = await ai.models.generateContent({
        model: 'gemini-flash-latest',
        contents: prompt,
        config: {
          systemInstruction: 'Você é o SuperBot AI Trader, um mentor e especialista sênior em negociação de criptomoedas e mercado financeiro. Responda de forma direta, técnica e prática em português.'
        }
      });
      
      return response.text?.trim() || 'Análise indisponível no momento.';
    } catch (err) {
      console.error('Gemini AI chat error:', err);
    }
  }

  return `SuperBot AI (Modo de Contingência): A API principal está indisponível no momento. 
Para sua pergunta "${userQuery}", considere sempre a gestão de risco primeiro. 
${ticker ? `Para ${ticker.symbol}, observe o perfil de volume (POC: ${ticker.rangeProfile.poc}) e a convergência com o Golden Pocket.` : 'Mantenha a cautela e observe a tendência macro.'}`;
}
